version: 2.1

orbs:
  cypress: cypress-io/cypress@1
  # heroku: circleci/heroku@0

workflows:
  test-and-deploy:
    jobs:
      - cypress/run:
          store_artifacts: true
          yarn: true
          start: npm start
          wait-on: 'http://localhost:3000'
      # - heroku/deploy-via-git:
      #     requires:
      #       - cypress/run
      #     filters:
      #       branches:
      #         only: main
