version: 2.1

orbs:
  cypress: cypress-io/cypress@2

workflows:
  test:
    jobs:
      - cypress/install:
          yarn: true
      - cypress/run:
          name: 'end-to-end tests'
          yarn: true
          requires:
            - cypress/install
          parallel: true
          parallelism: 4
          store_artifacts: true
          start: yarn start
          wait-on: 'http://localhost:3000'
