version: 2.1

orbs:
  cypress: cypress-io/cypress@2

workflows:
  test-and-deploy:
    jobs:
      - cypress/run:
          name: Run tests
          yarn: true
          parallel: true
          parallelism: 4
          store_artifacts: true
          start: yarn start
          wait-on: 'http://localhost:3000'
