version: 2.1

orbs:
  cypress: cypress-io/cypress@3

workflows:
  test:
    jobs:
      - cypress/run:
          name: 'TestE2E'
          package-manager: yarn
          executor: cypress/default
          start-command: yarn start
